-- ═══════════════════════════════════════════════════════════════════════
-- SRN Command Center — Phase 9 & 10 Seed
-- Phase 9: Cloud (AWS / GCP)
-- Phase 10: NLP / LLMs Expanded
-- Run AFTER supabase-master-migration.sql and phases-7-8-and-phase5-update.sql
-- Safe to run multiple times — fully idempotent (ON CONFLICT DO NOTHING)
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO learning_phases (id, sort_order, title, duration, accent_color, bg_color, text_color, milestone, resources, tracks, weeks, practice)
VALUES

-- ─── Phase 9: Cloud (AWS / GCP) ──────────────────────────────────────────────
(9, 8, 'Cloud — AWS / GCP', 'Weeks 19–24 (parallel)', '#0F6E56', 'rgba(15,110,86,0.13)', '#4ecfa0',
 'Deploy 1 ML model end-to-end on AWS SageMaker or GCP Vertex AI',
 '[{"label":"AWS Free Tier","url":"https://aws.amazon.com/free"},{"label":"AWS SageMaker docs","url":"https://docs.aws.amazon.com/sagemaker"},{"label":"GCP Free Tier","url":"https://cloud.google.com/free"},{"label":"GCP Vertex AI docs","url":"https://cloud.google.com/vertex-ai/docs"},{"label":"A Cloud Guru","url":"https://acloudguru.com"},{"label":"AWS ML Specialty","url":"https://aws.amazon.com/certification/certified-machine-learning-specialty"}]',
 '[{"label":"Cloud Fundamentals","topics":["IaaS vs PaaS vs SaaS — when to use each","Cloud resource hierarchy — accounts, projects, regions, zones","IAM — roles, policies, service accounts, least privilege","VPC basics — subnets, security groups, firewall rules","Object storage — S3 (AWS) or GCS (GCP) — buckets, versioning, lifecycle","Compute — EC2 / Compute Engine — instance types for ML","Serverless — Lambda / Cloud Functions — event-driven inference","Cost management — billing alerts, spot instances, preemptible VMs"]},{"label":"ML on Cloud","topics":["SageMaker / Vertex AI — managed training jobs","Managed notebooks — SageMaker Studio / Vertex Workbench","Model registry — versioning, staging, production","Batch inference vs real-time endpoint deployment","Auto-scaling inference endpoints","Cloud-based feature store — SageMaker Feature Store / Vertex Feature Store","ML Pipelines — SageMaker Pipelines / Vertex Pipelines","Model monitoring — data drift detection, performance alerts"]},{"label":"Data Engineering on Cloud","topics":["Cloud data warehouse — Redshift (AWS) or BigQuery (GCP)","Managed Kafka — MSK (AWS) or Pub/Sub (GCP) — real-time streaming","ETL pipelines — AWS Glue or Dataflow (GCP)","Data lake architecture — S3 + Glue catalog or GCS + Dataplex","Orchestration — MWAA (Managed Airflow AWS) or Cloud Composer","Infrastructure as Code basics — Terraform or CloudFormation","CI/CD for ML — CodePipeline (AWS) or Cloud Build (GCP)","Security for ML — encryption at rest/transit, VPC endpoints"]}]',
 '[{"label":"Week 19","goals":["Set up AWS Free Tier or GCP Free Tier account","IAM: create roles, attach policies, test least privilege","S3/GCS: create bucket, upload data, set lifecycle policy"]},{"label":"Week 20","goals":["SageMaker or Vertex: run a managed training job on a real dataset","Save model artifact to S3/GCS, register in model registry","Deploy model as real-time endpoint, test with curl/Postman"]},{"label":"Week 21","goals":["Build a SageMaker Pipeline or Vertex Pipeline: data → train → eval → deploy","Add model monitoring: enable data capture, set drift threshold","Write Terraform or CloudFormation for one resource (S3 bucket + Lambda)"]},{"label":"Week 22","goals":["BigQuery or Redshift: run 5 analytical queries on public dataset","Set up streaming pipeline: Pub/Sub → Dataflow → BigQuery (or Kinesis → Lambda → Redshift)","Cloud CI/CD: auto-deploy model on new training run via Cloud Build or CodePipeline"]},{"label":"Week 23","goals":["Cost review: analyze your cloud bill, identify optimisation opportunities","Spot/preemptible instances: retrain model using cost-saving compute","Full end-to-end: raw data in S3/GCS → training → endpoint → monitoring — all automated"]},{"label":"Week 24","goals":["Write README for your cloud ML project — architecture diagram, cost breakdown, results","Study AWS ML Specialty or GCP Professional ML Engineer exam guide (first 3 topics)","Mock: explain your cloud architecture to a non-technical person in 5 minutes"]}]',
 '[{"title":"Cloud Hands-On Exercises","problems":["Deploy a sklearn model as a real-time SageMaker or Vertex AI endpoint (not just notebook — production endpoint)","Build a SageMaker Pipeline / Vertex Pipeline with 4 stages: data validation → training → evaluation → conditional deployment","Set up data drift monitoring on a deployed endpoint — trigger alert when feature distribution shifts","Write a Lambda / Cloud Function that triggers model retraining when new data lands in S3/GCS","Create a Terraform config that provisions: S3 bucket + IAM role + SageMaker endpoint + CloudWatch alert"]},{"title":"Cloud Architecture Design Questions","problems":["Design a real-time recommendation system using AWS (Kinesis → Lambda → SageMaker endpoint → DynamoDB)","How would you reduce inference cost by 60% for a model getting 10M requests/day? (batching, caching, distillation, spot)","A model in production has degrading accuracy over 3 months — what cloud-native tools detect and fix this automatically?","Design a multi-region ML deployment with failover — how do you handle model consistency across regions?","You have 1TB of new training data weekly — design the automated retraining pipeline on GCP end to end"]}]'),

-- ─── Phase 10: NLP / LLMs Expanded ──────────────────────────────────────────
(10, 9, 'NLP / LLMs Expanded', 'Weeks 18–23 (parallel)', '#854F0B', 'rgba(133,79,11,0.13)', '#d4924a',
 'Build and deploy a RAG application with a vector database',
 '[{"label":"HuggingFace docs","url":"https://huggingface.co/docs"},{"label":"LangChain docs","url":"https://python.langchain.com/docs"},{"label":"OpenAI Cookbook","url":"https://cookbook.openai.com"},{"label":"Pinecone Learning Center","url":"https://www.pinecone.io/learn"},{"label":"LMSYS Chatbot Arena","url":"https://lmsys.org"},{"label":"Chip Huyen AI Engineering","url":"https://huyenchip.com/2023/04/11/llm-engineering.html"},{"label":"Papers With Code NLP","url":"https://paperswithcode.com/area/natural-language-processing"}]',
 '[{"label":"NLP Foundations + Modern Transformers","topics":["Text preprocessing — tokenization, BPE, WordPiece, SentencePiece","Word embeddings — Word2Vec, GloVe, FastText (conceptual)","Attention mechanism — scaled dot-product, multi-head attention","BERT architecture — bidirectional, MLM, NSP pretraining","GPT architecture — autoregressive, causal attention, next token prediction","T5 / BART — encoder-decoder, seq2seq tasks","Sentence Transformers — bi-encoders for semantic similarity","Evaluation metrics — BLEU, ROUGE, BERTScore, Perplexity"]},{"label":"LLM Engineering","topics":["Prompt engineering — zero-shot, few-shot, chain-of-thought, ReAct","LLM fine-tuning — full fine-tune vs parameter-efficient methods","LoRA and QLoRA — low-rank adaptation, quantization basics","Instruction tuning and RLHF — high-level concepts","LLM evaluation — hallucination detection, faithfulness, factuality","Context window management — chunking, summarization, sliding window","LLM serving — vLLM, TGI, batch inference, latency vs throughput","AI safety basics — alignment, red-teaming, guardrails"]},{"label":"RAG + Vector Databases","topics":["RAG architecture — retrieval augmented generation pipeline","Dense retrieval — DPR, bi-encoders, FAISS, approximate nearest neighbour","Vector databases — Pinecone, Weaviate, Chroma, pgvector — when to use each","Embedding models — text-embedding-ada-002, instructor, E5, BGE","Chunking strategies — fixed, semantic, hierarchical, sliding window","Hybrid search — dense + sparse (BM25) retrieval, reranking","Advanced RAG — HyDE, multi-query, self-RAG, corrective RAG","Evaluation of RAG — RAGAS framework, context relevance, answer faithfulness"]}]',
 '[{"label":"Week 18","goals":["Fine-tune DistilBERT on a custom classification task (not SST-2 — pick healthcare or finance domain)","Implement sentence similarity with sentence-transformers, build a semantic search over 1000 documents","BLEU and ROUGE: compute scores for a text summarization model"]},{"label":"Week 19","goals":["Prompt engineering: implement chain-of-thought on 5 reasoning problems, measure accuracy improvement","Build a simple RAG pipeline: PDF → chunk → embed → store in Chroma → retrieve → generate","LangChain: build a conversational Q&A bot with memory over a document set"]},{"label":"Week 20","goals":["LoRA fine-tuning: fine-tune a small LLM (Mistral 7B or LLaMA 3) on a custom dataset using QLoRA + 4-bit quantization","Evaluate hallucination: run 20 factual questions, measure hallucination rate before and after RAG","Vector database: migrate your RAG from Chroma to Pinecone or Weaviate, compare retrieval speed"]},{"label":"Week 21","goals":["Advanced RAG: implement HyDE (Hypothetical Document Embeddings) and measure retrieval quality improvement","Hybrid search: add BM25 sparse retrieval alongside dense, rerank with cross-encoder","Deploy your RAG app as a FastAPI endpoint — /ask endpoint that accepts question, returns answer + sources"]},{"label":"Week 22","goals":["RAGAS evaluation: run full evaluation suite (context precision, recall, answer faithfulness, answer relevance)","LLM serving: benchmark your model with vLLM vs naive inference — measure throughput improvement","Write a technical blog post or README about your RAG system — architecture, evaluation results, lessons learned"]},{"label":"Week 23","goals":["Full project: end-to-end RAG application deployed on cloud (AWS/GCP) with monitoring, evaluation, and CI/CD","Study 10 NLP interview questions (tokenization, attention, BERT vs GPT, fine-tuning trade-offs)","Mock: explain RAG architecture, trade-offs, and failure modes in 10 minutes to a non-ML audience"]}]',
 '[{"title":"NLP + LLM Hands-On","problems":["Fine-tune a BERT model on a domain-specific classification task — achieve >85% F1 — deploy as FastAPI endpoint","Build a semantic search engine over 5000 Wikipedia articles using sentence-transformers + FAISS — sub-100ms retrieval","Implement a RAG pipeline from scratch (no LangChain) — PDF ingestion → chunking → embedding → FAISS → GPT generation","QLoRA fine-tune Mistral 7B on a 1000-row instruction dataset — measure perplexity before and after","Evaluate a RAG system with RAGAS: report context precision, recall, answer faithfulness, and answer relevance scores"]},{"title":"LLM System Design","problems":["Design a customer support bot for a bank: 100K daily queries, <2s latency, must cite policy documents, zero hallucination on numbers","Design a code review assistant: ingests PR diffs, retrieves relevant coding standards, generates review comments — handle 500 PRs/day","Design a medical Q&A RAG system: how do you handle hallucination risk on drug dosage questions? What guardrails?","You have a fine-tuned LLM that costs $0.05 per query. Traffic is 10M queries/day. Design a caching + routing strategy to cut cost by 70%","How would you detect and mitigate prompt injection attacks in a production LLM application?"]}]')

ON CONFLICT (id) DO NOTHING;

-- Update sequence to stay ahead
SELECT setval('learning_phases_id_seq', 15);
