-- ═══════════════════════════════════════════════════════════════════════
-- SRN Command Center — v10.8 Additions
-- Run this in Supabase SQL Editor AFTER supabase-master-migration.sql
-- Safe to run multiple times — fully idempotent.
-- What this does:
--   1. Updates Phase 5 (MLOps) — expands ML System Design to full section
--   2. Inserts Phase 7 — SQL + Data Engineering
--   3. Inserts Phase 8 — Statistics + Probability
-- ═══════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────
-- PART A: Update Phase 5 — Expand ML System Design to full dedicated section
-- ───────────────────────────────────────────────────────────────────────
UPDATE learning_phases SET
  title       = 'MLOps + ML System Design',
  duration    = 'Weeks 17–24',
  milestone   = 'Deploy 1 model as REST API · Record a 45-min ML system design mock',
  resources   = '[{"label":"Made With ML","url":"https://madewithml.com"},{"label":"Chip Huyen — Designing ML Systems","url":"https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/"},{"label":"FastAPI docs","url":"https://fastapi.tiangolo.com"},{"label":"Docker docs","url":"https://docs.docker.com"},{"label":"Netflix Tech Blog","url":"https://netflixtechblog.com"},{"label":"Uber Engineering","url":"https://www.uber.com/en-IN/blog/engineering/"},{"label":"Airbnb Engineering","url":"https://medium.com/airbnb-engineering"}]',
  tracks      = '[{"label":"MLOps Essentials","topics":["MLflow — experiment tracking, model registry","Docker basics — containerize model","FastAPI — build & deploy model API","CI/CD with GitHub Actions","AWS SageMaker or GCP Vertex AI — end-to-end deployment","Model versioning and rollback strategies","Feature stores — what, why, how (Feast)","A/B testing and model monitoring in production"]},{"label":"ML System Design — Core Concepts","topics":["Training pipeline: data collection → preprocessing → training → serving","Online vs offline evaluation — metrics that matter","Handling data drift and concept drift in production","Designing for scale: low-latency inference, batching, caching","Feature store architecture — real-time vs batch features","Model serving patterns — shadow mode, canary, blue-green","Distributed training basics — data parallelism, model parallelism","Design interview framework — requirements → high-level → deep dive"]},{"label":"ML System Design — Case Studies","topics":["YouTube/Netflix recommendation system — two-tower model, ANN retrieval","Google/Uber ride pricing — real-time features, feedback loops","Instagram feed ranking — multi-stage ranking pipeline","Gmail spam detection — online learning, concept drift","Fraud detection system — latency constraints, imbalanced data","Airbnb search ranking — learning to rank, position bias","Twitter/X timeline — candidate generation, ranking, real-time serving","Ad click-through rate prediction — large sparse features, embedding tables"]}]',
  weeks       = '[{"label":"Week 17","goals":["MLflow: log experiments, metrics, artifacts for a sklearn model","Understand run comparison and model registry","Docker: write Dockerfile, build image, run container"]},{"label":"Week 18","goals":["FastAPI: build /predict endpoint for a model","Add input validation with Pydantic","Build GitHub Actions CI pipeline that runs tests on push"]},{"label":"Week 19","goals":["Deploy Dockerized FastAPI to Render or Railway (free tier)","AWS/GCP: set up account, understand IAM, S3/GCS basics","Feature store concept: implement a simple version with Redis or dict"]},{"label":"Week 20","goals":["Chip Huyen Chapter 1–4: ML system lifecycle, data engineering","Chip Huyen Chapter 5–7: feature engineering, training, evaluation","Netflix Tech Blog: read 2 ML engineering case studies"]},{"label":"Week 21","goals":["ML System Design: YouTube recommendation — write full design doc","ML System Design: Fraud detection — write full design doc","Uber Engineering: read surge pricing / demand forecasting post"]},{"label":"Week 22","goals":["ML System Design: Instagram feed ranking — write full design doc","ML System Design: Gmail spam detection — write full design doc","Airbnb Engineering: read search ranking ML post"]},{"label":"Week 23","goals":["ML System Design: Ad CTR prediction — write full design doc","ML System Design: Twitter timeline — write full design doc","Chip Huyen Chapter 8–11: deployment, monitoring, infrastructure"]},{"label":"Week 24","goals":["Record a 45-min mock ML system design interview (YouTube recommendation or Ad CTR)","Review recording: identify gaps, time management issues","Full mock with a peer or self-review: do all 10 system designs from memory outline"]}]',
  practice    = '[{"title":"MLOps Hands-On","problems":["Train a classifier, log all params/metrics to MLflow, compare 3 runs","Write a Dockerfile for a FastAPI app that loads a .pkl model and serves /predict","Build a GitHub Actions workflow: lint → test → build Docker image on PR","Deploy a model API to a free cloud service (Render/Railway) and share the live URL","Implement a simple feature store: precompute user features daily, serve in <5ms at inference"]},{"title":"ML System Design — 10 Must-Do Designs","problems":["Design YouTube/Netflix video recommendations (100M users, real-time personalization)","Design a fraud detection system (latency < 50ms, 1:1000 class imbalance)","Design Instagram/TikTok feed ranking (multi-stage: retrieval → ranking → re-ranking)","Design Google/Bing ad click-through rate prediction (sparse features, embedding tables)","Design a real-time ride pricing system like Uber Surge (demand forecasting + feedback loop)","Design a document search engine with semantic similarity (dense retrieval, ANN index)","Design Gmail spam detection (online learning, concept drift, low false positive rate)","Design a model monitoring system that detects data drift and triggers retraining","Design Airbnb search ranking (learning to rank, A/B testing, position bias correction)","Design Twitter/X timeline (candidate generation, diversity, real-time serving)"]}]'
WHERE id = 5;

-- ───────────────────────────────────────────────────────────────────────
-- PART B: Insert Phase 7 — SQL + Data Engineering
-- ───────────────────────────────────────────────────────────────────────
INSERT INTO learning_phases (id, sort_order, title, duration, accent_color, bg_color, text_color, milestone, resources, tracks, weeks, practice)
VALUES
(7, 6, 'SQL + Data Engineering', 'Weeks 5–8 (parallel)', '#1D6B8C', 'rgba(29,107,140,0.13)', '#56c3e8',
 'Solve 30 SQL Medium on DataLemur',
 '[{"label":"DataLemur","url":"https://datalemur.com"},{"label":"StrataScratch","url":"https://platform.stratascratch.com"},{"label":"Mode SQL Tutorial","url":"https://mode.com/sql-tutorial"},{"label":"BigQuery Sandbox","url":"https://cloud.google.com/bigquery/docs/sandbox"},{"label":"PySpark Docs","url":"https://spark.apache.org/docs/latest/api/python"}]',
 '[{"label":"Core SQL","topics":["SELECT, WHERE, GROUP BY, ORDER BY, HAVING — drill 20 problems","JOINs — INNER, LEFT, RIGHT, FULL OUTER, SELF JOIN","Subqueries and correlated subqueries","CTEs — WITH clause, recursive CTEs","Window functions — ROW_NUMBER, RANK, DENSE_RANK, NTILE","LAG, LEAD, FIRST_VALUE, LAST_VALUE","PARTITION BY + ORDER BY patterns","Date/time functions — DATEDIFF, DATE_TRUNC, EXTRACT"]},{"label":"Data Engineering Concepts","topics":["Data warehouse concepts — star schema, snowflake schema","Fact vs dimension tables — design patterns","ETL vs ELT pipelines — when to use each","Query optimization — EXPLAIN, indexes, partitioning","BigQuery basics — dataset, table, query cost","PySpark — RDDs vs DataFrames, transformations vs actions","Spark SQL — read/write Parquet, CSV, JSON","dbt basics — models, tests, sources (optional)"]},{"label":"Interview SQL Patterns","topics":["Consecutive days / streaks — window function pattern","Running totals and cumulative sums","Median, percentile, mode calculations","Pivoting rows to columns (CASE WHEN + GROUP BY)","Finding duplicates, gaps, and islands","Top-N per group pattern","Month-over-month growth calculations","Retention and cohort analysis queries"]}]',
 '[{"label":"Week 5","goals":["DataLemur: 10 Easy SQL (warm-up)","Core JOINs: write 5 real queries on a dataset","CTE practice: rewrite 3 subqueries as CTEs"]},{"label":"Week 6","goals":["Window functions: ROW_NUMBER, RANK — 8 problems","LAG/LEAD: write MoM revenue growth query","StrataScratch: 10 Medium SQL problems"]},{"label":"Week 7","goals":["BigQuery sandbox: run 3 real queries on public datasets","PySpark: load CSV, filter, groupBy, write to Parquet","DataLemur: 10 more Medium problems"]},{"label":"Week 8","goals":["Full data pipeline: ingest CSV → transform with SQL → aggregate → output","Star schema design: model a retail dataset (fact/dim tables)","Review + DataLemur milestone: 30 Medium total"]}]',
 '[{"title":"Must-Solve SQL Interview Problems","problems":["User activity streak — find users with 3+ consecutive active days using LAG","Top 3 products per category — ROW_NUMBER + PARTITION BY","Month-over-month revenue growth — LAG with DATE_TRUNC","Median salary per department — PERCENTILE_CONT window function","Customer retention — cohort analysis with DATE_DIFF and GROUP BY","Duplicate email detection with COUNT(*) > 1 and GROUP BY","Running balance: cumulative sum of transactions per user","Pivot monthly sales: CASE WHEN + MAX(CASE) pattern"]},{"title":"Data Engineering Exercises","problems":["Write a PySpark job: read CSV → filter nulls → groupBy → write Parquet","Design a star schema for an e-commerce dataset (orders, products, customers)","Write a BigQuery query on public dataset: top 10 NYC taxi pickup zones by revenue","Build a simple ETL: Python script that extracts from CSV, transforms with Pandas, loads to PostgreSQL","Write an EXPLAIN plan for a slow query and add appropriate index"]}]')
ON CONFLICT (id) DO NOTHING;

-- ───────────────────────────────────────────────────────────────────────
-- PART C: Insert Phase 8 — Statistics + Probability
-- ───────────────────────────────────────────────────────────────────────
INSERT INTO learning_phases (id, sort_order, title, duration, accent_color, bg_color, text_color, milestone, resources, tracks, weeks, practice)
VALUES
(8, 7, 'Statistics + Probability', 'Weeks 7–10 (parallel)', '#5A3B8C', 'rgba(90,59,140,0.13)', '#b088ef',
 'Design and analyze a full mock A/B test end to end',
 '[{"label":"StatQuest (YouTube)","url":"https://www.youtube.com/@statquest"},{"label":"Khan Academy Stats","url":"https://www.khanacademy.org/math/statistics-probability"},{"label":"Seeing Theory","url":"https://seeing-theory.brown.edu"},{"label":"Think Stats (free book)","url":"https://greenteapress.com/wp/think-stats-2e"},{"label":"Naked Statistics","url":"https://www.goodreads.com/book/show/17986418-naked-statistics"}]',
 '[{"label":"Probability Foundations","topics":["Sample space, events, probability axioms","Conditional probability — P(A|B) = P(A∩B)/P(B)","Bayes theorem — prior, likelihood, posterior","Independence vs mutual exclusivity","Counting: permutations, combinations","Discrete distributions — Binomial, Poisson, Geometric","Continuous distributions — Normal, Uniform, Exponential","Central Limit Theorem — why it matters for ML"]},{"label":"Statistical Inference","topics":["Point estimates vs interval estimates","Confidence intervals — construction and interpretation","Hypothesis testing — null vs alternative hypothesis","Type I error (false positive) and Type II error (false negative)","p-value — what it is and what it is NOT","Statistical power and sample size calculation","t-test, chi-squared test, z-test — when to use which","Bonferroni correction for multiple testing"]},{"label":"A/B Testing & Applied Stats","topics":["A/B test design: control vs treatment, randomization","Minimum detectable effect (MDE) and sample size","Novelty effect and peeking problem","Sequential testing and early stopping","CUPED — variance reduction technique","Multi-armed bandit vs A/B testing tradeoffs","Causal inference basics — confounding, selection bias","Regression to the mean — common interview pitfall"]}]',
 '[{"label":"Week 7","goals":["Probability basics: 15 problems (Bayes, conditional probability, counting)","Distributions: Normal, Binomial, Poisson — compute by hand + Python","StatQuest: watch Probability Fundamentals playlist"]},{"label":"Week 8","goals":["Hypothesis testing: t-test on a real dataset in Python","Confidence intervals: compute for mean and proportion","StatQuest: p-value, hypothesis testing videos"]},{"label":"Week 9","goals":["Design a mock A/B test: define hypothesis, MDE, sample size, alpha/beta","Simulate the A/B test in Python (scipy.stats)","Chi-squared test: analyze categorical outcomes"]},{"label":"Week 10","goals":["Full mock A/B test analysis: collect simulated data → test → interpret → report","CLT demonstration: simulate sampling distributions in Python","Review: 20 statistics interview questions from Google/Meta style guides"]}]',
 '[{"title":"Probability Problems (Interview Style)","problems":["You flip a fair coin 10 times. What is P(exactly 6 heads)? (Binomial)","Given P(rain)=0.3, P(umbrella|rain)=0.8, P(umbrella|no rain)=0.1 — find P(rain|umbrella) using Bayes","In a dataset of 1000 users, 50 have condition X. If a test has 90% sensitivity and 95% specificity, what is the PPV?","You roll two dice. What is P(sum > 9 | first die = 4)?","A website has 1000 visitors/day. On average 5 crash. Model this with Poisson. P(0 crashes in a day)?"]},{"title":"A/B Testing Scenarios","problems":["You run an A/B test for 2 weeks. Control CTR = 5%, Treatment CTR = 5.5%, n=10,000 per group. Is this significant? (z-test)","Your A/B test shows p=0.04 but business says the lift is too small to ship. What do you recommend?","Explain the peeking problem: why checking significance daily inflates Type I error","Calculate the minimum sample size needed to detect a 2% lift (from 10% baseline) with 80% power and α=0.05","You have 5 variants to test. Why does running 5 separate A/B tests inflate the false positive rate? How do you fix it?"]}]')
ON CONFLICT (id) DO NOTHING;

-- ───────────────────────────────────────────────────────────────────────
-- Update sequence (phases now go up to 8)
-- ───────────────────────────────────────────────────────────────────────
SELECT setval('learning_phases_id_seq', 12);
